export default {
  definitions: {},
  $schema: 'http://json-schema.org/draft-07/schema#',
  $id: 'http://example.com/root.json',
  type: 'object',
  title: 'The Root Schema',
  properties: {
    currentUser: {
      $id: '#/properties/currentUser',
      type: 'object',
      title: 'The Currentuser Schema',
      required: ['email', 'name'],
      properties: {
        email: {
          $id: '#/properties/currentUser/properties/email',
          type: 'string',
          title: 'The Email Schema',
          default: '',
          examples: ['imellabellashop@gmail.com'],
          pattern: '^(.*)$',
        },
        name: {
          $id: '#/properties/currentUser/properties/name',
          type: 'string',
          title: 'The Name Schema',
          default: '',
          examples: ['Ella Bella'],
          pattern: '^(.*)$',
        },
      },
    },
    emailGroups: {
      $id: '#/properties/emailGroups',
      type: 'array',
      title: 'The Emailgroups Schema',
      items: {
        $id: '#/properties/emailGroups/items',
        type: 'object',
        title: 'The Items Schema',
        required: ['id', 'name', 'recipients'],
        properties: {
          id: {
            $id: '#/properties/emailGroups/items/properties/id',
            type: 'integer',
            title: 'The Id Schema',
            default: 0,
            examples: [0],
          },
          name: {
            $id: '#/properties/emailGroups/items/properties/name',
            type: 'string',
            title: 'The Name Schema',
            default: '',
            examples: ['name1'],
            pattern: '^(.*)$',
          },
          recipients: {
            $id: '#/properties/emailGroups/items/properties/recipients',
            type: 'array',
            title: 'The Recipients Schema',
            items: {
              $id: '#/properties/emailGroups/items/properties/recipients/items',
              type: 'object',
              title: 'The Items Schema',
              required: ['email', 'firstName', 'lastName', 'preferred'],
              properties: {
                email: {
                  $id:
                    '#/properties/emailGroups/items/properties/recipients/items/properties/email',
                  type: 'string',
                  title: 'The Email Schema',
                  default: '',
                  examples: ['ferdelamad@gmail.com'],
                  pattern: '^(.*)$',
                },
                firstName: {
                  $id:
                    '#/properties/emailGroups/items/properties/recipients/items/properties/firstName',
                  type: 'string',
                  title: 'The Firstname Schema',
                  default: '',
                  examples: ['Fernando'],
                  pattern: '^(.*)$',
                },
                lastName: {
                  $id:
                    '#/properties/emailGroups/items/properties/recipients/items/properties/lastName',
                  type: 'string',
                  title: 'The Lastname Schema',
                  default: '',
                  examples: ['De La Madrid'],
                  pattern: '^(.*)$',
                },
                preferred: {
                  $id:
                    '#/properties/emailGroups/items/properties/recipients/items/properties/preferred',
                  type: 'string',
                  title: 'The Preferred Schema',
                  default: '',
                  examples: ['Fernando'],
                  pattern: '^(.*)$',
                },
              },
            },
          },
        },
      },
    },
    recipients: {
      $id: '#/properties/recipients',
      type: 'array',
      title: 'The Recipients Schema',
      items: {
        $id: '#/properties/recipients/items',
        type: 'object',
        title: 'The Items Schema',
        required: ['email', 'firstName', 'lastName', 'preferred'],
        properties: {
          email: {
            $id: '#/properties/recipients/items/properties/email',
            type: 'string',
            title: 'The Email Schema',
            default: '',
            examples: ['ferdelamad@gmail.com'],
            pattern: '^(.*)$',
          },
          firstName: {
            $id: '#/properties/recipients/items/properties/firstName',
            type: 'string',
            title: 'The Firstname Schema',
            default: '',
            examples: ['Fernando'],
            pattern: '^(.*)$',
          },
          lastName: {
            $id: '#/properties/recipients/items/properties/lastName',
            type: 'string',
            title: 'The Lastname Schema',
            default: '',
            examples: ['De La Madrid'],
            pattern: '^(.*)$',
          },
          preferred: {
            $id: '#/properties/recipients/items/properties/preferred',
            type: 'string',
            title: 'The Preferred Schema',
            default: '',
            examples: ['Fernando'],
            pattern: '^(.*)$',
          },
        },
      },
    },
    templates: {
      $id: '#/properties/templates',
      type: 'array',
      title: 'The Templates Schema',
      items: {
        $id: '#/properties/templates/items',
        type: 'object',
        title: 'The Items Schema',
        required: [
          'greeting',
          'id',
          'injections',
          'message',
          'name',
          'salutation',
          'subjectLine',
          'templateName',
          'type',
        ],
        properties: {
          greeting: {
            $id: '#/properties/templates/items/properties/greeting',
            type: 'string',
            title: 'The Greeting Schema',
            default: '',
            examples: ['Hi'],
            pattern: '^(.*)$',
          },
          id: {
            $id: '#/properties/templates/items/properties/id',
            type: 'integer',
            title: 'The Id Schema',
            default: 0,
            examples: [5],
          },
          injections: {
            $id: '#/properties/templates/items/properties/injections',
            type: 'object',
            title: 'The Injections Schema',
            required: ['title', 'message'],
            properties: {
              title: {
                $id: '#/properties/templates/items/properties/injections/properties/title',
                type: 'string',
                title: 'The Title Schema',
                default: '',
                examples: ['Message from the sublime'],
                pattern: '^(.*)$',
              },
              message: {
                $id: '#/properties/templates/items/properties/injections/properties/message',
                type: 'string',
                title: 'The Message Schema',
                default: '',
                examples: [
                  'Thank you so much for that thing you did for me. I really appreciate your help. Thanks again!',
                ],
                pattern: '^(.*)$',
              },
            },
          },
          message: {
            $id: '#/properties/templates/items/properties/message',
            type: 'string',
            title: 'The Message Schema',
            default: '',
            examples: [
              'Thank you so much for that thing you did for me. I really appreciate your help. Thanks again!',
            ],
            pattern: '^(.*)$',
          },
          name: {
            $id: '#/properties/templates/items/properties/name',
            type: 'string',
            title: 'The Name Schema',
            default: '',
            examples: ['Galvanize Letterhead'],
            pattern: '^(.*)$',
          },
          salutation: {
            $id: '#/properties/templates/items/properties/salutation',
            type: 'string',
            title: 'The Salutation Schema',
            default: '',
            examples: ['Warm regards,'],
            pattern: '^(.*)$',
          },
          subjectLine: {
            $id: '#/properties/templates/items/properties/subjectLine',
            type: 'string',
            title: 'The Subjectline Schema',
            default: '',
            examples: ['Hello there!'],
            pattern: '^(.*)$',
          },
          templateName: {
            $id: '#/properties/templates/items/properties/templateName',
            type: 'string',
            title: 'The Templatename Schema',
            default: '',
            examples: ['letterhead'],
            pattern: '^(.*)$',
          },
          type: {
            $id: '#/properties/templates/items/properties/type',
            type: 'string',
            title: 'The Type Schema',
            default: '',
            examples: ['techmentor'],
            pattern: '^(.*)$',
          },
        },
      },
    },
  },
};
